---
version: '2'

services:
  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    hostname: ksqldb-server
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: b-2.mskatin.pjdcv1.c7.kafka.us-east-1.amazonaws.com:9092,b-1.mskatin.pjdcv1.c7.kafka.us-east-1.amazonaws.com:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_COMMAND_TOPIC_REPLICATION_FACTOR: 2
      KSQL_KSQL_SINK_TOPIC_REPLICATION_FACTOR: 2
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 2

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:latest
    container_name: ksqldb-cli
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

  ksqldb-ui:
    image: deniskrumko/ksqldb-ui:latest
    environment:
      APP_CONFIG: /config.toml
    volumes:
      - ./development.toml:/config.toml
    ports:
      - 8080:8080